# Image-1: Install misc. build tools + ansible
FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

RUN set -xe; \
    apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https \
        git \
        make \
        python-virtualenv \
        software-properties-common \
    \
    && apt-add-repository -y ppa:ansible/ansible \
    && apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        ansible \
    \
    && apt-get autoremove -y && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*
